# 第一階段: 構建階段
FROM golang:1.18-rc-alpine AS builder

# 設置工作目錄
WORKDIR /app

# 複製所有源代碼
COPY . .

# 初始化 Go 模組
RUN go mod init study-k8s && go mod tidy

# 構建 Go 應用
RUN go build -o main

# 第二階段: 運行階段
FROM alpine:3.15.0-rc.4

WORKDIR /app

# 從構建階段中複製已編譯的二進制文件
COPY --from=builder /app/main .

# 暴露服務端口
EXPOSE 8080

# 運行應用
ENTRYPOINT ["./main"]
